spring.application.name=TaskManagementToolB-7

# =========================
# MYSQL CONFIG
# =========================

spring.datasource.url=jdbc:mysql://localhost:3306/taskmanagementtool?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=190820
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================
# JPA
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# =========================
# SERVER
# =========================

server.port=8080


# =========================
# EMAIL
# =========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# =========================
# CLOUDINARY
# =========================

cloudinary.cloud-name=YOUR-CLOUDINARY-NAME
cloudinary.api-key=YOUR-API_KEY
cloudinary.api-secret=YOUR-SECRET

# File Upload Path
file.upload-dir=uploads/

#Cloud
cloudinary.cloud-name=YOUR-CLOUDINARY-NAME
cloudinary.api-key=YOUR-API_KEY
cloudinary.api-secret=YOUR-SECERT